server:
  port: 8085

info:
  app:
    name: APS QR Code Web Service
    description: This web service can be used to generate and read QR Code image
    version: 1.0.0

management:  endpoints:    web:      base-path: /appmonitoring      exposure:        include: "*"